# Generated by Django 6.0 on 2026-01-04 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('ml_index', models.IntegerField(primary_key=True, serialize=False)),
                ('track_id', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('track_name', models.CharField(max_length=255)),
                ('artist_name', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=100)),
            ],
            options={
                'indexes': [models.Index(fields=['track_id'], name='music_track_track_i_85f96e_idx'), models.Index(fields=['track_name', 'artist_name'], name='music_track_track_n_a7efb2_idx')],
            },
        ),
    ]
